# Generated by Django 3.2.18 on 2023-04-18 09:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230412_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=210, unique=True)),
                ('slug', models.SlugField(max_length=210, unique=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='plaaceholder', max_length=255, verbose_name='image')),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
